import streamlit as st

from core.dashboard_models import DashboardSnapshot


# =========================================================
# Helpers
# =========================================================

def _premium_map(snapshot: DashboardSnapshot) -> dict:
    """
    Build a lookup table for ForwardPremiumAnalysis.

    Key:
        (strike_price, option_type)

    Value:
        ForwardPremiumAnalysis
    """

    premium_map = {}

    if not snapshot.premium_analysis:
        return premium_map

    for item in snapshot.premium_analysis:
        premium_map[
            (
                item.strike_price,
                item.option_type.upper(),
            )
        ] = item

    return premium_map


# =========================================================
# Render
# =========================================================

def render(
    snapshot: DashboardSnapshot,
) -> None:
    """
    Render live option chain with:

    - Market LTP
    - Black-Scholes theoretical premium
    - Premium deviation
    - OI
    - IV

    The UI does not perform Black-Scholes calculations.
    It consumes premium analytics generated by the
    analytics layer.
    """

    st.subheader("📋 Live Option Chain")

    market = snapshot.market

    option_chain = market.option_chain

    if not option_chain:
        st.warning(
            "Option chain not available."
        )
        return

    atm = market.atm_strike

    # -----------------------------------------------------
    # Sort Option Chain
    # -----------------------------------------------------

    option_chain = sorted(
        option_chain,
        key=lambda x: x.strike_price,
    )

    # -----------------------------------------------------
    # Find ATM
    # -----------------------------------------------------

    atm_index = next(
        (
            i
            for i, item in enumerate(option_chain)
            if item.strike_price == atm
        ),
        len(option_chain) // 2,
    )

    # -----------------------------------------------------
    # ATM ±5
    # -----------------------------------------------------

    start = max(
        0,
        atm_index - 5,
    )

    end = min(
        len(option_chain),
        atm_index + 6,
    )

    window = option_chain[start:end]
    
    
    premium_lookup = _premium_map(snapshot)
    recommendation = snapshot.ai.recommendation if snapshot.ai else None

    # -----------------------------------------------------
    # Header
    # -----------------------------------------------------

    st.caption(
        f"ATM Strike : {atm}"
    )

    headers = st.columns(9)

    headers[0].markdown("**Call OI**")
    headers[1].markdown("**Call LTP**")
    headers[2].markdown("**Call BS**")
    headers[3].markdown("**Call IV**")
    headers[4].markdown("**Strike**")
    headers[5].markdown("**Put IV**")
    headers[6].markdown("**Put BS**")
    headers[7].markdown("**Put LTP**")
    headers[8].markdown("**Put OI**")

    st.divider()

    # -----------------------------------------------------
    # Rows
    # -----------------------------------------------------

    for option in window:

        cols = st.columns(9)

        # -----------------------------------------
        # Black-Scholes lookup
        # -----------------------------------------

        call_bs = premium_lookup.get(
            (option.strike_price, "CE")
        )

        put_bs = premium_lookup.get(
            (option.strike_price, "PE")
        )

        # -----------------------------------------
        # CALL
        # -----------------------------------------

        cols[0].write(
            f"{option.call_oi:,}"
        )

        call_is_selected = bool(
            recommendation
            and recommendation.option_type == "CE"
            and recommendation.strike_price == option.strike_price
        )
        put_is_selected = bool(
            recommendation
            and recommendation.option_type == "PE"
            and recommendation.strike_price == option.strike_price
        )

        call_ltp = f"{option.call_ltp:.2f}"
        cols[1].markdown(f"**⭐ {call_ltp}**" if call_is_selected else call_ltp)

        if call_bs and call_bs.forward_bs_premium is not None:
            cols[2].write(f"{call_bs.forward_bs_premium:.2f}")
        else:
            cols[2].write("N/A")

        cols[3].write(
            f"{option.call_iv:.2f}"
        )

        # -----------------------------------------
        # STRIKE
        # -----------------------------------------

        if option.strike_price == atm:

            cols[4].markdown(f"**🟨 {option.strike_price}**")

        else:

            cols[4].write(
                option.strike_price
            )

        # -----------------------------------------
        # PUT
        # -----------------------------------------

        cols[5].write(
            f"{option.put_iv:.2f}"
        )

        if put_bs and put_bs.forward_bs_premium is not None:
            cols[6].write(f"{put_bs.forward_bs_premium:.2f}")
        else:
            cols[6].write("N/A")

        put_ltp = f"{option.put_ltp:.2f}"
        cols[7].markdown(f"**⭐ {put_ltp}**" if put_is_selected else put_ltp)

        cols[8].write(
            f"{option.put_oi:,}"
        )
